### ISSUE TITLE
Web Application Is NOT RESPONSIVE .

### ISSUE THREAD

**Issue by Mohit5Upadhyay** [piug-07/blogzen-OpenSource#1]
I want to contribute Under GSSoC'24 . Please assign this task to me to make the web application responsive  with other devices.

**Comment by nandu-99** [comment]
please assign this issue to me, i can make this web application responsive by using grid system and flex system, and writing media queries

**Comment by webdevgithubcoder** [comment]
I want to correct this issue, please assign it to me.

**Comment by Harsh-Vardhan-Yadav-03** [comment]
I can solve this issue, please assign this to me

**Comment by michellecordovi** [comment]
Please assign this issue to me as I would like to contribute under GSSoC'24 .  I would be capable of making this site responsive via a grid based layout and media queries where I will adjust the layout as needed for desktop, tablet, and mobile.

**Comment by shnwz-solves** [comment]
Hi @Mohit5Upadhyay , I would like to contribute. Please assign me this. Thankyou!

**Comment by deepak9285** [comment]
hello sir can you please assign it to me i would like to contribute in this

**Comment by Aayushi23jain** [comment]
I want to contribute Under GSSoC'24 . Please assign this task to me to make the web application responsive with other devices.

**Comment by anupa-rb** [comment]
Hi there, I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.

**Comment by vanirastogi** [comment]
Hi can u please assign it to me too
