### ISSUE TITLE
ChatBot is not Showing properly

### ISSUE THREAD

**Issue by Harshsaini001** [piug-07/blogzen-OpenSource#10]
When we open the Chatbot section on website half of the part of the chatbot section in hidden.
![Screenshot 2024-05-09 221044](https://github.com/piug-07/blogzen-OpenSource/assets/127672737/337391ae-011d-4c70-b59e-bebd0e65f897)

**Comment by adrocks1234** [comment]
Please assign me this issue under GSSOC'24 @piug-07

**Comment by Scrapper700** [comment]
Please assign me this issue under GSSOC'24 @piug-07

**Comment by vijaykanwal90** [comment]
assign me this I will implement google' gemini api for chatbot
