### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [piug-07/blogzen-OpenSource#11]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behavior, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Kindly assign me this issue, so i can work towards it under GSSOC 24

**Comment by Aryan-joh** [comment]
can you please add the level?

**Comment by Aryan-joh** [comment]
please assign this project to me as i am a GSSoC contribter

**Comment by mfatima05** [comment]
Is this issue done? @anshgautam-github

**Comment by mfatima05** [comment]
I am the mentor of this project and I have merged your PR
