### ISSUE TITLE
BUG: The web page is not responsive.

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [piug-07/blogzen-OpenSource#110]
@piug-07 I would like to work under this issue. Please assign it to me under gssoc24. 
You can see the current condition of the site below.

![Screenshot_20240512_075649_Chrome](https://github.com/piug-07/blogzen-OpenSource/assets/139672976/3b5b186b-b9fb-46c0-8395-1c1920e2a188)

![Screenshot_20240512_075658_Chrome](https://github.com/piug-07/blogzen-OpenSource/assets/139672976/aa9d06be-6fbe-45da-8163-c733031246f7)

I am willing to solve this issue. Please assign me.

**Comment by snehathakur07** [comment]
Hello! I'd like to take on the challenge of resolving this issue. I have experience in creating responsive websites, including the official website for the **5th International Conference on Machine Learning, Image Processing, Network Security, and Data Sciences**, held at NIT Hamirpur. I'll investigate the non-responsiveness of the website and implement the necessary changes to ensure it displays properly across various devices. Assigning this issue to me would be great—I'm eager to tackle it and improve the user experience. Thanks!
