### ISSUE TITLE
change the color of sending text in chatbot.not visible

### ISSUE THREAD

**Issue by ishaa18** [piug-07/blogzen-OpenSource#118]
the color of sending text in chat box is black and bg is blue so it is not visible clearly.
![WhatsApp Image 2024-05-12 at 13 03 39_1c5323b1](https://github.com/piug-07/blogzen-OpenSource/assets/145281412/adb01fb5-bfa1-4f96-aa13-b0c5a57acbff)

**Comment by Prachiii8287** [comment]
I would like to solve this issue. Please assign me

**Comment by Aryan-Singla** [comment]
Please assign this issue to me I have Raised the PR
