### ISSUE TITLE
Buttons under the search bar are inconsistent 

### ISSUE THREAD

**Issue by Madhu-mac** [piug-07/blogzen-OpenSource#13]
[](url)we need to fix the UI of the buttons when its clicked. It has to be consistent with relevant lengths

current behaviour :

![Screenshot_20240509_230446](https://github.com/piug-07/blogzen-OpenSource/assets/99901964/af39ba35-f881-4ea2-a2ee-480a7ffe5421)

![Screenshot_20240509_230500](https://github.com/piug-07/blogzen-OpenSource/assets/99901964/9c10c12f-ff0d-414c-94e3-e7531ef33c80)

Expected Design:

![Screenshot_20240509_230509](https://github.com/piug-07/blogzen-OpenSource/assets/99901964/50fb5481-40ae-4107-8b44-8fe387f6be6a)

**Comment by Madhu-mac** [comment]
@piug-07 Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by nishant0708** [comment]
please assign me this issue i can fix this issue

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to me, I am good at designing as well
