### ISSUE TITLE
Add scroll back to top button 

### ISSUE THREAD

**Issue by Sneha123-zudo** [piug-07/blogzen-OpenSource#14]
I want to add scroll back to top button this website.
Please assign me this issue under GSSOC'24

**Comment by nishant0708** [comment]
can you assign me this issue

**Comment by Aditi-Gopinath** [comment]
I would love to contribute to this issue.

Could you assign the issue to me under GSSoC'24.

**Comment by Prakhar-bansal1** [comment]
It will be my pleasure if you assign me for this issue. I'll try my best and give 100% to it..
