### ISSUE TITLE
Callender is not working properly in dark mode

### ISSUE THREAD

**Issue by Amitesh-Mishra-AM** [piug-07/blogzen-OpenSource#154]
![image](https://github.com/piug-07/blogzen-OpenSource/assets/86422382/0fedc325-5f76-4395-8ba2-6f45e6b39150)

## Thank You

**Comment by shrutisachan08** [comment]
@piug-07 I am contributor in GSSoC'24 . I can work on this issue and it could be fixed by:
Using leverage browser feature as it could detect the preference of system in the dark mode .
Hence , Kindly assign me this issue under the label of GSSoC'24  .

**Comment by Kashif581** [comment]
Hi @piug-07!
I hope your doing well. I have solved this issue of calendar not looking properly in dark mode. please check out my pull request, add the the label of GSSoC'24.
Thank you.
