### ISSUE TITLE
login is not looking perfectly in dark mode and sign-up button is not working

### ISSUE THREAD

**Issue by Amitesh-Mishra-AM** [piug-07/blogzen-OpenSource#155]
![image](https://github.com/piug-07/blogzen-OpenSource/assets/86422382/01a29dc6-b0b3-44f1-bfa2-8c07dc5de071)
## Thank You

**Comment by PadmalathaKasireddy** [comment]
I'm excited to contribute on this issue of login features and signup button action. I'm keen to help enhance the login & sign-up features and user experience. Looking forward to the opportunity to discuss further.
