### ISSUE TITLE
Add Hover Effect on Blogs to lift them slightly.

### ISSUE THREAD

**Issue by MastanSayyad** [piug-07/blogzen-OpenSource#156]
Hi @piug-07,
I've noticed that the blogs in the website **lack a hover effect**, which could enhance user interaction and improve the overall visual appeal of the website.

![image](https://github.com/piug-07/blogzen-OpenSource/assets/101971980/ac9cdb0b-f899-4c28-b05d-b879d417c7a5)

**Benefits:**
- Improved user experience.
- Aesthetics.
- Visual Attraction.

 I propose to add a hover effect to lift the boxes slightly when the mouse is placed over them, creating a more engaging browsing experience.

**Comment by aasthabagrawal** [comment]
I would love to fix this under GSSOC'24 because I have prior experience on this.

**Comment by Aradhya-005** [comment]
I would like to work on this . Please assign it to me
