### ISSUE TITLE
White background element of Navbar in Darkmode

### ISSUE THREAD

**Issue by Prashant-2024** [piug-07/blogzen-OpenSource#158]
Is there an existing issue for this?

- [x] I have searched the existing issues

![image](https://github.com/piug-07/blogzen-OpenSource/assets/140724156/14e5cc39-9e01-4ee3-9375-0f0f373ac0b9)

What happened?
- irrelevant Orange color in navbar, Violet will be good choice
- unequal size background margins to elements, bad UX experience

@piug-07  I would request you to assign this issue to me under GSSOC'24.

Record
 
- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by niteshbca** [comment]
Please assign me to task
