### ISSUE TITLE
Add Navigation Link for "All" in Navbar to navigate back to the "All" section

### ISSUE THREAD

**Issue by MastanSayyad** [piug-07/blogzen-OpenSource#185]
Hi @piug-07 ,
I've noticed that in the navbar, there is an **"All" section that displays all the blogs** on the website. However, **after clicking on other navigation sections such as technology, branding, news, AI, etc., there isn't a way to navigate back to the "All" section**. 

https://github.com/piug-07/blogzen-OpenSource/assets/101971980/c6723695-2072-46e4-8399-3b67e8e1cd50

As it is giving a bad impression to users
I believe adding a navigation link for "All" in the navbar would improve user navigation and provide a more seamless browsing experience and improve user experience.

I'd like to take on the task, Could you please **assign this issue to me under GSSoC'24** so I can start working on it?

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24

**Comment by DevNandini02** [comment]
@piug-07 I would like to work on this issue. please assign this task to me under gssoc' 24.
