### ISSUE TITLE
Calendar is not working

### ISSUE THREAD

**Issue by Surajit0573** [piug-07/blogzen-OpenSource#19]
Want to add Calendar Sections and its backend, Please assign me under Gssoc'24.

**Comment by Aditi-Gopinath** [comment]
Could you assign it to me under GSSOC'24 

I would like to add a user friendly calender section.

**Comment by AmrutaJayanti** [comment]
Can you please assign me this project under gssoc'2024

**Comment by Laksh-01** [comment]
Can you please assign me this project under gssoc'2024 I would like to add a user friendly calender section.

you can also check my linkedin https://www.linkedin.com/in/lakshsachdeva/

**Comment by Manaswini123456** [comment]
Kindly assign me with this issue.

**Comment by ShubhamSingh4620** [comment]
I would love to solve this issue kindly assign me this

**Comment by harshitpnd12** [comment]
please assign me this issue

**Comment by Aditi-Gopinath** [comment]
I have added a calender and created a pull request, Please review.

**Comment by Anshika-Gochar** [comment]
please assign this to me under GSSoc'24
