### ISSUE TITLE
Adding hover Effect to Various buttons and Cards .

### ISSUE THREAD

**Issue by Mohit5Upadhyay** [piug-07/blogzen-OpenSource#2]
I want to work and contribute under GSSoC'24 . Please assign it to me . I will surely add hover effect to various buttons and card with proper gapping between them .

**Comment by solanki505** [comment]
I want to work on this issue under GSSoc'24, please assign me this.

**Comment by nandu-99** [comment]
@Mohit5Upadhyay Please assign this issue to me, i can resolve this issue by adding the grid system to cards and also the hover effects to cards to make it visually appealing and also adding the borders to cards will be better

**Comment by MattipaPoojitha** [comment]
I would like to contribute to this issue of adding "hover Effect to Various buttons and Cards". I already have experience in web development and worked on these effects in my previous project and made it successful, soo I kindly request you to approve my contribution 
Thank you 😊!!

**Comment by kamalesh-og** [comment]
Hi
I would like to work on this issue for adding the "Hover Effect to Various Buttons and Cards". I have worked with a project on this functionality earlier, so this could be a good opportunity for me to contribute to your project.
Thank You

**Comment by webdevgithubcoder** [comment]
I want to correct this issue under GSSOC'24,please assign this to me.

**Comment by niteshbca** [comment]
Please assign me this task. Solved the all button related problem.

**Comment by SadafKausar2025** [comment]
I want to work on this issue under GSSoc'24, please assign me this.

**Comment by Harsh-Vardhan-Yadav-03** [comment]
Please  assign this issue to me ,I can solve  the hover related problems.

**Comment by shuhaki** [comment]
i would love to work on this issue.i have very good experience in fronted part, i did some good projects related to this issue so, could you please assaign it to me i will do it

**Comment by T1rth1** [comment]
i would like to work upon this issue so please assign me this issue

**Comment by MelissaSequeira** [comment]
I can do it...Plz consider me for the task
https://melissasequeira.github.io/fashionweb.github.io/

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @piug-07 under GSSoC'24. It would be a pleasure for me to contribute to this issue. Kindly assign this issue to me.

**Comment by alishasingh06** [comment]
@piug-07 please assign me this task

**Comment by n14rishitha** [comment]
Hi @piug-07 
I can resolve this issue .This hover effect makes website more responsive . 
so please assign this task to me under the label gssoc24 and level1,2,or 3
