### ISSUE TITLE
[DOCUMENTATION}-Updating and Enhancement

### ISSUE THREAD

**Issue by AdityaP700** [piug-07/blogzen-OpenSource#208]
>The Contributing File needs modification and enhancement which would visually appeal to the Clients.

> The License File needs to be readable and visually appealing

**Comment by AdityaP700** [comment]
I can help you out in making the documentation more user interactive and readable ,thus i hope you will assign me this issue .Thank you

**Comment by mfatima05** [comment]
I have merged your PR.
