### ISSUE TITLE
Blog cards overlap with each other and Blog Title hides behind navbar

### ISSUE THREAD

**Issue by RashidSiddiqui2004** [piug-07/blogzen-OpenSource#22]
Currently, on the blog page of BlogZen, there is an issue where **_blog cards overlap with each other_**, leading to a cluttered and messy appearance. Additionally, the **_Blog Title gets hidden behind the navbar_**, affecting the readability and user experience.

_Steps to Reproduce Issue 1:_

1. Go to the blogs page.
2. Scroll through the blog cards.
3. Observe the overlapping of cards.

**_Image:_** 

![Blog desc overlaps](https://github.com/piug-07/blogzen-OpenSource/assets/124426004/361f325f-07a4-4306-b0a8-277a6f181e1e)

_Steps to Reproduce Issue 2:_

1. Go to blog - "How Technology Has Changed the Way We Work" or any other blog.
2. Observe the overlapping of title with navbar.

**_Image:_**

![title Hides](https://github.com/piug-07/blogzen-OpenSource/assets/124426004/7a445616-4db1-4959-b3af-7450c5066364)

**Comment by RashidSiddiqui2004** [comment]
Please assign this task to me under **GSSOC'24.**

**Comment by Sahil21dev** [comment]
Hey author @piug-07  ,
I possess a strong skillset in front-end development, particularly in UI/UX design. I have experience working with HTML, CSS, JavaScript, and frameworks like Bootstrap .I'm confident that I can effectively address the mentioned UI issue and contribute positively to Blogzen's development.
Therefore please assign the issue .
