### ISSUE TITLE
Enhancement of the footer section

### ISSUE THREAD

**Issue by Nayanika1402** [piug-07/blogzen-OpenSource#24]
I would really appreciate @piug-07 if you allow me to work in making the footer section look more attractive and user-friendly.Kindly assign me this task under GSSOC'24.

**Comment by aashkaaaaaa** [comment]
i want working of this issue, please assign me

**Comment by Uma-129** [comment]
i updated the code with enhancements in the footer section

**Comment by gayathrik23** [comment]
@piug-07  can you assign this issue to me under Gssoc'24

**Comment by nsk6704** [comment]
I kindly request you to assign this issue to me, an aspiring web developer certified by freeCodeCamp in Web Design and have also interned at a company named Codsoft.

Also I have contributed to roadmap.sh's documentation which is one of the most starred repository on GitHub!!

Here is my LinkedIn Profile for more information!

https://www.linkedin.com/in/saketh-kashyap-nagendra/
