### ISSUE TITLE
Text overflowing

### ISSUE THREAD

**Issue by suma30** [piug-07/blogzen-OpenSource#246]
![Screenshot 2024-05-20 134421](https://github.com/piug-07/blogzen-OpenSource/assets/112741893/53166766-e676-469d-91c2-21055ac9fd72)

As shown in the above pic, text is overflowing from the container, I can fix it
please assign me this issue under GSSOC'24 @piug-07

**Comment by Komalpreet-Kaur112** [comment]
Hey @piug-07 
I would like to work to this issue. Please assign it to me.

**Comment by mfatima05** [comment]
I have merged your pr
