### ISSUE TITLE
[bug]:calender spell to corrected as calendar

### ISSUE THREAD

**Issue by ishaa18** [piug-07/blogzen-OpenSource#251]
the spelling of calendar is "calender"  which needs to be corrected.
![Screenshot (51)](https://github.com/piug-07/blogzen-OpenSource/assets/145281412/11527f86-27f9-417a-bca7-573e8a481735)

**Comment by mfatima05** [comment]
I have merged your PR and I am closing this issue.

**Comment by ishaa18** [comment]
I have contributed under GSSOC'24 can you label my PR under gssoc please.
