### ISSUE TITLE
Adding Button (Scroll top) ⬆️

### ISSUE THREAD

**Issue by HK853** [piug-07/blogzen-OpenSource#257]
![image](https://github.com/piug-07/blogzen-OpenSource/assets/113816862/09484854-75b9-49e4-97ad-797e0dba7db0)
## Functionality:
Clicking the button triggers a smooth scroll animation that takes the user back to the top of the page. This can be implemented using JavaScript and CSS for the smooth scrolling effect.

## Scenario:
A user is reading through a lengthy blog post on a website. After scrolling down several sections, they decide they want to revisit the navigation menu or start reading another post. Instead of manually scrolling back up, they can click the "Scroll to Top" button.

**Comment by dvnshi** [comment]
I would like to work on this please assign it to me

**Comment by HK853** [comment]
Hi @piug-07 ,  
     Done with this feature you can check it. How it is looking.

**Comment by mfatima05** [comment]
how?

**Comment by HK853** [comment]
Sorry I don't understand what you say ,but you can check or review my pull request which is  PR #285
