### ISSUE TITLE
Changing buttons on the home page 

### ISSUE THREAD

**Issue by Rakshit-gen** [piug-07/blogzen-OpenSource#28]
Buttons on the homepage look not so good when in dark theme.
We can make them look prettier!

Please assign this issue to me. I am a GSSoC 2024 contributor.

![issue22](https://github.com/piug-07/blogzen-OpenSource/assets/64471316/3f6cd6fe-180a-462a-9324-959ea91c1c9a)

**Comment by Sailesh3000** [comment]
I am a GSSOC'24 Contributor I have already updated the styles of the buttons in the Home page and made a PR please assign me this issue.

**Comment by MelissaSequeira** [comment]
Pls Assign me this task:
you can check my repos where i made websites responsive:
https://melissasequeira.github.io/fashionweb.github.io/
https://melissasequeira.github.io/My_Portfoliogithub.io/

**Comment by sahithinandikula** [comment]
@plug-07 I am interested in working on this issue , I hope my request would be considered
