### ISSUE TITLE
Add a hover effect

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [piug-07/blogzen-OpenSource#29]
Adding hover effect on the All, technology, Ai button

**Comment by nishant0708** [comment]
please assign me this issue

**Comment by sahithinandikula** [comment]
would like to work on this and will add the hover effect as mentioned

**Comment by DaminiTechie** [comment]
please assign me this issue

**Comment by codersumit29** [comment]
Please assign the issue

**Comment by Hemav009** [comment]
Hello 
Please assign me this issue. I would like to add a hover effect on  buttons below search bar.
GSSoC'24

**Comment by T1rth1** [comment]
Hey, i would like to work on this issue, please assign me this issue  
GSSOC'24

**Comment by anythingkartik** [comment]
Hi Team,
I'm Kartik, and I'm excited to join the project. While I'm new to open source. I would love to work on this problem set.
Please consider assigning me this issue. I'm looking forward to adding my touch to the project.

Here's my LinkedIn profile for further contact: https://www.linkedin.com/in/itskartikgupta/

**Comment by MelissaSequeira** [comment]
Pls Assign me this task:
you can check my repos where i made websites responsive:
https://melissasequeira.github.io/fashionweb.github.io/
https://melissasequeira.github.io/My_Portfoliogithub.io/

**Comment by DivyaNareshkumarPatel** [comment]
Is there a way to enhance user interaction on the website? Currently, there's no hover effect implemented on interactive elements.

I propose adding a hover effect to interactive elements to improve user engagement and provide visual feedback.

Implementing hover effects will not only enhance the aesthetic appeal of the website but also make it more interactive and user-friendly.

Please assign me this task. I'm a GSSOC '24 contributor eager to contribute.

**Comment by Hemav009** [comment]
> Hello Please assign me this issue. I would like to add a hover effect on buttons below search bar. GSSoC'24

Kindly assign this task to me.
I can solve it
Thank you!

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @piug-07 under GSSoC'24. It would be a pleasure for me to contribute to this issue. Kindly assign this issue to me.
