### ISSUE TITLE
Issue in LogIn page , during Dark mode .

### ISSUE THREAD

**Issue by Mohit5Upadhyay** [piug-07/blogzen-OpenSource#3]
Please assign  this task to me  . I will surely solve this issue of Text is white during dark mode so it doesn't appear to  the user .

**Comment by nandu-99** [comment]
@Mohit5Upadhyay  please assign this issue to me, i have already made the local setup, and i have seen this issue.... in dark mode, text is converting into white color, which is causing the issue, i can resolve this issue.

**Comment by niteshbca** [comment]
Please assign this task to me. And solved the all problem.

**Comment by Abhishek0732** [comment]
Please assign this task to me I will fix dark mode, login page and nav bar

**Comment by Aditi-Gopinath** [comment]
I'm excited to work on this issue.
I'll resolve the issue being caused for in login page during dark mode.

Could you assign it to me under GSSOC'24

**Comment by AshutoshKumar0206** [comment]
Please assign this task to me. I will make sure that the icons which are not visible in login page at dark mode are made visible

**Comment by mfatima05** [comment]
@Mohit5Upadhyay @nandu-99 will you work on this issue?
