### ISSUE TITLE
Add basic email validation to subscribe to newsletter

### ISSUE THREAD

**Issue by Ashish-1020** [piug-07/blogzen-OpenSource#306]
It take any input as email as you can see

https://github.com/piug-07/blogzen-OpenSource/assets/161131072/de1bbfbc-a72e-4eca-baed-f114932979a1

after changes it will ask to enter valid email

![Screenshot 2024-05-31 071723](https://github.com/piug-07/blogzen-OpenSource/assets/161131072/1aee79fa-afe5-435d-acbe-4aa76589e5a0)

Pls assign me this issue

**Comment by mfatima05** [comment]
You can work on this issue.

**Comment by mfatima05** [comment]
Your PR has been merged and now I am closing this issue
