### ISSUE TITLE
Changing twitter logo

### ISSUE THREAD

**Issue by harikasayani** [piug-07/blogzen-OpenSource#307]
I am GSSOC'24 Contributor.
I observed that there is incorrect twitter logo in web page.
I want to work on this issue.
Please assign me this task.

**Comment by mfatima05** [comment]
kindly attach the image for better understanding the issue

**Comment by harikasayani** [comment]
Ok

**Comment by harikasayani** [comment]
![Screenshot (144)](https://github.com/piug-07/blogzen-OpenSource/assets/143275265/04c1ca63-0b3c-46cd-893f-3f49b6f4114f)

**Comment by mfatima05** [comment]
I think the twitter logo is fine as it is, so I am closing this issue. You can work on other created issues.
