### ISSUE TITLE
Improving UI of Login/Signup page.

### ISSUE THREAD

**Issue by yashi-15** [piug-07/blogzen-OpenSource#4]
- I can improve the UI of Login/Signup modal for the website.

- Also, I will take care of its UI for both Light/Dark modes.

I would like to work on this issue under GSSoC'24. Kindly assign it to me.

**Comment by hetvipopat** [comment]
hi there!!
I'm interested working on this issue (GSSOC'24)

**Comment by Sathya-reddy1658** [comment]
i would work on this issuer and make it look more professional as well ass responsive , assign me this issue

**Comment by shuhaki** [comment]
i would love to work on this issue.i have very good experience in fronted part, i did some good projects related to this issue so, could you please assaign it to me i will do it

**Comment by VisNcoder** [comment]
I would like to work on this issue please assign It to me.

**Comment by PallaviGudupallavi** [comment]
I would like to contribute to fix this, Consider me in!

**Comment by Deathnote45** [comment]
I would like to fix this issue. assign me in

**Comment by Aryan-joh** [comment]
hii i would like to fix this issue a i know the required skills used in this

**Comment by richasriva** [comment]
Hi , I can fix this issue , Kindly assign it to me

**Comment by deepthi-1673** [comment]
Hi, I am willing to contribute to this issue please assign it to me.

**Comment by vaishnavip27** [comment]
Hey @piug-07  I can work on the enhancement of the page as a designer and a developer. Please assign this issue to me. Looking forward for your approval
