### ISSUE TITLE
Improve Smoothness of Hover Effect

### ISSUE THREAD

**Issue by Shashanktriathi1703** [piug-07/blogzen-OpenSource#538]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

# Problem
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by codeseker** [comment]
I am resolving this issue
