### ISSUE TITLE
There is no Hover effect on the Login button

### ISSUE THREAD

**Issue by Sheryar-bit** [piug-07/blogzen-OpenSource#54]
There is no Hover effect on the Login button, I can work on this issue and make it enhancing. please assign it to me. GSSOC'24
@piug-07 

![Screenshot 2024-05-10 204155](https://github.com/piug-07/blogzen-OpenSource/assets/132276541/a6aa94d4-eb2f-4027-a536-082a9c6fb983)

**Comment by Sheshank-singh** [comment]
Hello @piug-07 i would love to improve and adding effect on the login button . Please assigned me this issue 
Thank you

**Comment by navyatripathics** [comment]
@piug-07 please assign me this issue

**Comment by anurag2787** [comment]
Hello @piug-07 can you assign this work to me
I am contributing under GSSoC24

**Comment by ArpitaBarode0702** [comment]
Hello @piug-07 can you please assign this issue to me.

**Comment by Sheryar-bit** [comment]
The issue is resolved Thank you.
