### ISSUE TITLE
Adding about us in navbar

### ISSUE THREAD

**Issue by Souvik34** [piug-07/blogzen-OpenSource#57]
Adding about us in navbar and arranging it properly with the alignment. Assign me the issue and will deliver it the stipulated time

**Comment by Sheshank-singh** [comment]
Hello @piug-07  please assigned me this issue to adding the about us in navbar

**Comment by DivyaNareshkumarPatel** [comment]
Is there a way for users to easily access information about the project? Currently, there's no direct link to an "About Us" page in the navbar.

I propose adding an "About Us" link to the navbar to provide users with easy access to basic information about the project's purpose and vision..

Please assign me this task. I'm a GSSOC '24 contributor eager to contribute.

**Comment by Bhoomii2003** [comment]
Please assign this issue to me , i will solve this , in very less time

**Comment by Muskansahuincredible** [comment]
please assign me this

**Comment by Anup2601** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24.

**Comment by Aleena-Memon** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24.

**Comment by shifas1** [comment]
Hello @piug-07, can you please assign me this issue under GSSoC'24.

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to me
