### ISSUE TITLE
Change Cursor type of home page list.

### ISSUE THREAD

**Issue by sau-mili** [piug-07/blogzen-OpenSource#6]
The nav bar on homepage has normal cursor, user cannot differentiate it now. I wish to change it to Link cursor. Please assign this to me. @piug-07

**Comment by anshgautam-github** [comment]
I want to work on this issue, can u assign this to me?

**Comment by sau-mili** [comment]
@piug-07 worked and added pull-req please check.

**Comment by Aditi-Gopinath** [comment]
I would love to work on this issue and kick-start my open source contribution.

Could u assign it to me under GSSoC'24

**Comment by aanchalpahuja18** [comment]
Would love to contribute in this kindly assign me @piug-07

**Comment by DrishnaTrivedi** [comment]
@piug-07 please assign this issue to me under GSSoC.

**Comment by alishasingh06** [comment]
@piug-07 please assign me this issue

**Comment by mfatima05** [comment]
@sau-mili are you working on this?

**Comment by sau-mili** [comment]
The PR hasn't been reviews by the PA

**Comment by mfatima05** [comment]
I am the mentor of this project and I have merged your PR and I am closing this issue

**Comment by sau-mili** [comment]
Thank you
