### ISSUE TITLE
FEATURE: Addition of Scroll to top button

### ISSUE THREAD

**Issue by Sourabh782** [piug-07/blogzen-OpenSource#717]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

Addition of scroll to top button, When we reach to bottom of page we can click it to go to the top

![Screenshot 2024-08-09 141205](https://github.com/user-attachments/assets/9127fc60-6d91-4f4c-8a5c-8ce1985cbc71)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

**Comment by Vipul-Ydv** [comment]
is it still available ?
