### ISSUE TITLE
No Code of Conduct

### ISSUE THREAD

**Issue by Dhruv-Pattel** [piug-07/blogzen-OpenSource#84]
This repository has no code of conduct. any open-source project needs to set clear standards for behavior. It promotes inclusivity, prevents misconduct, fosters accountability, and maintains a positive environment.

Please assign this issue to me.

**Comment by nsk6704** [comment]
I kindly request you to assign this issue to me, an aspiring web developer certified by freeCodeCamp in Web Design and have also interned at a company named Codsoft.

Also I have contributed to roadmap.sh's documentation which is one of the most starred repository on GitHub!!

Here is my LinkedIn Profile for more information!

https://www.linkedin.com/in/saketh-kashyap-nagendra/
